version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.7

    working_directory: ~/repo

    steps:
      # Step 1: checkout repo from GitHub
      - checkout
      # Step 2: install dependencies located in requirements.txt
      - run:
          name: install dependencies
          command: pip install -r requirements.txt
      # Step 3: run linter and tests
      - run:
          name: run tests
          command: |
            flake8 --statistics
            pytest

workflows:
  main:
    jobs:
      - build
